-- Online membership application queue (member_applications table).
-- Safe to re-run: CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS `member_applications` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `wpforms_entry_id` varchar(64) NOT NULL,
  `wpforms_form_id` int unsigned DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `reviewed_by` int unsigned DEFAULT NULL,
  `approved_member_id` int unsigned DEFAULT NULL,
  `application_kind` varchar(16) NOT NULL DEFAULT 'unknown',
  `form_season` varchar(32) DEFAULT NULL,
  `suggested_renewal_type` varchar(16) DEFAULT NULL,
  `suggested_renewal_year` smallint unsigned DEFAULT NULL,
  `matched_member_id` int unsigned DEFAULT NULL,
  `match_confidence` varchar(16) DEFAULT NULL,
  `match_method` varchar(32) DEFAULT NULL,
  `first_name` varchar(255) NOT NULL DEFAULT '',
  `last_name` varchar(255) NOT NULL DEFAULT '',
  `middle_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `emergency_contact_name` varchar(255) DEFAULT NULL,
  `emergency_contact_relationship` varchar(64) DEFAULT NULL,
  `emergency_contact_phone` varchar(64) DEFAULT NULL,
  `address_street` varchar(255) DEFAULT NULL,
  `address_street2` varchar(255) DEFAULT NULL,
  `address_city` varchar(128) DEFAULT NULL,
  `address_state` varchar(64) DEFAULT NULL,
  `address_postal_code` varchar(32) DEFAULT NULL,
  `ama_number` varchar(64) DEFAULT NULL,
  `ama_expiration` date DEFAULT NULL,
  `faa_number` varchar(64) DEFAULT NULL,
  `faa_expiration` date DEFAULT NULL,
  `membership_type_slot` tinyint unsigned DEFAULT NULL,
  `notes` text,
  `payment_total` decimal(10,2) DEFAULT NULL,
  `payment_initiation` decimal(10,2) DEFAULT NULL,
  `payment_processing_fee` decimal(10,2) DEFAULT NULL,
  `payment_gateway` varchar(64) DEFAULT NULL,
  `payment_transaction_id` varchar(128) DEFAULT NULL,
  `payment_status` varchar(32) DEFAULT NULL,
  `file_ama_verification_url` varchar(512) DEFAULT NULL,
  `file_faa_registration_url` varchar(512) DEFAULT NULL,
  `file_badge_photo_url` varchar(512) DEFAULT NULL,
  `file_signature_url` varchar(512) DEFAULT NULL,
  `raw_payload` json DEFAULT NULL,
  `rejection_reason` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wpforms_entry_id` (`wpforms_entry_id`),
  KEY `status` (`status`),
  KEY `matched_member_id` (`matched_member_id`),
  KEY `approved_member_id` (`approved_member_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `system_config` (`config_key`, `config_value`) VALUES
  ('application_webhook_secret', '');
